/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TestResponse implements Serializable {

    @ColumnAlias("USER_ID")
    private BigInteger userId;
    @ColumnAlias("USERNAME")
    private String username;
    @ColumnAlias("PASSWORD")
    private String password;
    @ColumnAlias("ROLE")
    private String role;
    @ColumnAlias("TENANT_ID")
    private BigInteger tenantId;

    public BigInteger getUserId() {
        return this.userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public BigInteger getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(BigInteger tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestResponse)) return false;
        final TestResponse testResponse = (TestResponse) o;
        return Objects.equals(getUserId(), testResponse.getUserId()) &&
                Objects.equals(getUsername(), testResponse.getUsername()) &&
                Objects.equals(getPassword(), testResponse.getPassword()) &&
                Objects.equals(getRole(), testResponse.getRole()) &&
                Objects.equals(getTenantId(), testResponse.getTenantId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUserId(),
                getUsername(),
                getPassword(),
                getRole(),
                getTenantId());
    }
}
